### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by diego898** [hoelzro/tw-full-text-search#2]
Hey, I'm not sure what caused this, but now when I try to generate the index, I get the following error in my console:

```
TypeError: Cannot read property 'Selection Constructors' of undefined
    at e.MutableBuilder.e.Builder.add ($:/plugins/hoelzro/full-text-search/lunr.min.js:7)
    at updateTiddler ($:/plugins/hoelzro/full-text-search/shared-index.js:202)
    at eval ($:/plugins/hoelzro/full-text-search/shared-index.js:99)
    at step ($:/plugins/hoelzro/full-text-search/shared-index.js:39)
    at Object.eval [as next] ($:/plugins/hoelzro/full-text-search/shared-index.js:20)
    at fulfilled ($:/plugins/hoelzro/full-text-search/shared-index.js:11)
    at <anonymous>
```

**Comment by hoelzro** [comment]
Yikes! Thanks for the report - are you familiar with the developer console? If so, could you run this chunk of code, reload the page, and try again to see if it helps?

```js
$tw.modules.execute('$:/plugins/hoelzro/full-text-search/localforage.min.js').clear().then(function() { console.log('index cleared') })
```

**Comment by diego898** [comment]
after running that, and refreshing, I was able to generate the index. How could it have gotten corrupted? And should there be a button in the control panel to run that in case it happens again? thanks!

**Comment by diego898** [comment]
bump!

**Comment by hoelzro** [comment]
@diego898 Sorry, this fell off of my radar!  I don't know how the index could've gotten corrupted - I can try to look into the stack trace you posted, but since the lunr.js file is minified it probably won't help me figure it out =(  I'll make the code more robust in the near future - maybe I'll just have it build the index from scratch if it encounters an error during an incremental update.

**Comment by hoelzro** [comment]
Note to self: just bundle the unminified lunr.js source for this to help with debugging?

**Comment by hoelzro** [comment]
Note to self: it must be some `[...]` field access in `lunr.Builder.add`?

**Comment by hoelzro** [comment]
@diego898 BTW, is "Selection Constructors" a title or tag of one of your tiddlers?

**Comment by hoelzro** [comment]
@diego898 Also, have you seen this problem come up again? Which browser are you using?

**Comment by diego898** [comment]
I havent seen it again, on either chrome or firefox. and "Selection constructor" is the name of a tiddler

**Comment by hoelzro** [comment]
Ok, thanks for the info - that helps a lot!

**Comment by hoelzro** [comment]
@diego898 Also, was this the first time you tried to generate the index after installing a newer version of the plugin?

**Comment by diego898** [comment]
Hm - Im not sure. I dont remember when it popped up. I guess if you cant replicate it we can just close for now and Ill reopen if it pops up again? thanks for looking into it!

**Comment by hoelzro** [comment]
@diego898 Thanks for reporting and for the information - I have a good idea _where_ it happened, but I'm not really sure _why_.  I'll keep it in the back of my mind - I'm hoping it was just a one-off thing, but I'm really curious what happened!
