### ISSUE TITLE
Misspelled auto-index file path

### ISSUE THREAD

**Issue by dnebauer** [hoelzro/tw-full-text-search#37]
Line 40 of `control-panel.tid` has a typo in the file path:

```
<$set name="autoIndexTiddler" value="$:/plugins/hoelzro/full-text-seach/auto-index">
```

The subdirectory `full-text-seach` is missing the __r__ in __seach__.

**Comment by hoelzro** [comment]
@dnebauer Thanks for letting me know! I've pushed a correction to master.
