### ISSUE TITLE
Full support of lunr's additional features

### ISSUE THREAD

**Issue by diego898** [hoelzro/tw-full-text-search#5]
Hey @hoelzro,

I love this plugin, and want it to become part of the core of TW eventually! Jeremy indicated he is also looking at lunr-based solutions. 

In line with that, it would be awesome if this plugin could fully support the following features lunr also supports:

* Scoring
  * Results are already ordered by this - it might be useful to display this as well (you already have this on future plans_

* Wildcards
  * This **kind** of works, depending on where I place it. For example, if I type `title:format*`, I get all tiddlers titled with Formatting and format in their title. But if I type `title:format*ing` I get no results.

* Fields
  * This already works out of the box! I can say `tags:tableofcontents` and it works. I can also do `tags:tableofcontents title:getting` to find all tiddlers tagged `tableofcontents` OR with `getting` in their title.

* Boosts
  * This would be great, cant really figure out a good way to test right now.

* Fuzzy
  * this was recently implemented - wonderful!

* Term Presence
  * I dont think this works, especially in combination with the other terms. 

I recognize that this is a lot! I just figured I would report back the results of my testing in this "wish list"!

Side-note: What do you think of the relationship between this library and filtering?

**Comment by diego898** [comment]
Hey @hoelzro, as I understand it from reading:

https://lunrjs.com/guides/searching.html

wildcards and term presence are already implemented in the library. They just need to be exposed in TW.

Term Presence is basically lunr's AND. So a term MUST be present if it has a `+` and must NOT be present if it has a `-`

**Comment by hoelzro** [comment]
Ah, ok - is term presence a new feature?  Since I'm just calling lunr's query function, you _should_ be able to just type in the `+` character for it to work - I probably need to update lunr.js, though.

**Comment by diego898** [comment]
Im not sure if its new, but when I tried it with `+customize` nothing came up.


**NOTE**: I forgot to mention above, all of the tests are down on a local copy of TW with this plugin installed.

**Comment by diego898** [comment]
My comment about filtering was more an observation, that this search plugin is very powerful and could replace/augment many things currently done with filtering in TW

**Comment by hoelzro** [comment]
I just checked - I've been using lunr.js 2.1.4, whereas term presence was added to 2.2.0.  I'll make an issue to add this!

**Comment by hoelzro** [comment]
Regarding filtering, do you think the existing `ftsearch` filter would be good enough, or should I make additional filters?

**Comment by diego898** [comment]
Sorry Rob, what is `ftsearch`? I was just observing that right now in TW (without this plugin) I use a lot of filtering, things like: `[tag[testing]regexp[mystring]]`, etc. This search plugin lets you also achieve many of the same goals that someone would use filtering for.

**Comment by hoelzro** [comment]
@diego898 Oh, sorry! `ftsearch` is the filter that this plugin provides that basically powers the whole thing.

BTW, do you have any interest/time in contributing code to this project? If so, I can always add you as a contributor!

**Comment by hoelzro** [comment]
@diego898 Ok, that's understandable.  Any code contribution is most welcome, but no pressure - just the feedback you've been giving me so far has been great!

**Comment by diego898** [comment]
Hey @hoelzro Im seeing some bugs in the latest version.

![image](https://user-images.githubusercontent.com/742407/44170416-ead57480-a09c-11e8-9d5f-fbf23dae0c45.png)

![image](https://user-images.githubusercontent.com/742407/44170433-fa54bd80-a09c-11e8-9522-167d16cb6bc6.png)


![image](https://user-images.githubusercontent.com/742407/44170452-08a2d980-a09d-11e8-99bc-2400fbdac376.png)

![image](https://user-images.githubusercontent.com/742407/44170508-34be5a80-a09d-11e8-8012-764d71b9454c.png)

as you can see, the formatting of results is strange, and Im not sure fuzzy matching is working correctly.

**Comment by hoelzro** [comment]
Thanks for the report @diego898  - I'll have a look!

**Comment by hoelzro** [comment]
@diego898 Is this just the wiki from tiddlywiki.com with the FTS plugin added?  I just tried that and it looks ok; would it be possible to share the wiki you're seeing this on?

**Comment by hoelzro** [comment]
No, I'm not =(  What browser are you using?  Could you send me the HTML file you're working with?

Also, regarding the fuzzy matching, what results are you seeing that you didn't expect to, or what's missing from the results that you expected to see?

**Comment by diego898** [comment]
Hey @hoelzro how do I send it to you? 

For the fuzzy matching, I was searching for "learning", but some of the first results that came up didn't have anything close to that word as far as I could tell? (maybe Im wrong?)

Also, the resutls are all displayed in a single line

Also when searching for "tiddly" why did it only bring up one result?

Also for `title:tid*l` why did it not bring up everything with tiddly in the title?

**Comment by hoelzro** [comment]
@diego898 You should be able to attach a file to this issue (there's a little blurb describing how at the bottom of the reply box) - if that doesn't work, you can send it to my e-mail address, which you can find on my site, https://hoelz.ro.

By the way, which browser are you using? Do you have any extensions enabled in that browser?

I don't see that single line behavior when I import the plugin into https://tiddlywiki.com; if you can get me that HTML file, I can dig in and try to figure out what's going on.

As far as the search results go, let's handle the display issues first and then we can move on to those; I have a feeling it has something to do with how the index is built.

**Comment by hoelzro** [comment]
Thanks for sending me the file @diego898 - I realized right away what the problem was!  I didn't notice that you were using the _advanced_ search; that's a bug I've had for a while but completely forgot about!

**Comment by hoelzro** [comment]
I've filed that away as #8.

**Comment by diego898** [comment]
@hoelzro ah I see. Sorry, should have made that clearer! Should I repost my results under regular search?

**Comment by hoelzro** [comment]
@diego898 Do regular search results render the same way for you, or do those look ok?

**Comment by diego898** [comment]
They look fine on regular search

**Comment by hoelzro** [comment]
Ok, good - I'll whip up a patch within the next few days!

**Comment by hoelzro** [comment]
@diego898 I have - I think it's nice to have alternatives, and IMO fuzzy search and FTS occupy different parts of a similar niche.  I didn't have an entirely cold reception when I announced FTS on the group, but I would guess that part of it comes down to @TheDiveO's attention to detail and design. The TwFuseJs demo wiki is _much_ nicer looking than mine!  It would also help if I made a release in the near future 😅

Feature-wise, it would be nice if FTS maintained the index entirely without user intervention - maybe that would be good for a new version!

(@TheDiveO sorry for mentioning you out of nowhere, but if you have any ideas on how to improve TW-FTS, I would love to hear them!)

**Comment by hoelzro** [comment]
@diego898 Regarding those search results for `title:tid*l` and `lerning~2` above - what are you trying to use the plugin to do?  I just want to make sure I fully understand.  I'm assuming for the former you want to match any tiddler whose title has a word that has "tid", followed by zero or more characters, then "l" in it, and for the latter you only want to match `tag:learning` even with the spelling mistake?

**Comment by hoelzro** [comment]
@diego898 ping

**Comment by diego898** [comment]
Hey @hoelzro sorry for the delay - Im trying to use `title:tid*l` to find all tiddlers whose title contain the string `tid---ANY LENGTH INCLUDING ZERO CHARACTERS---l` in their title, as you said. For `lerning~2` should include all tiddlers with the text "learning" inside them (not just the tag?)

**Comment by diego898** [comment]
yup!

**Comment by hoelzro** [comment]
Ok - so I think that's going to be a problem. =(  Since lunr.js stems everything, we don't keep `settle` in the database anywhere - it gets reduced to `settl`.  I'm not sure how lunr's author intended wildcards to handle this; I'm going to do a little research and see if there's a recommended solution!

**Comment by diego898** [comment]
awesome rob! Ill give it a try! thanks for your continued work on this!

**Comment by hoelzro** [comment]
@diego898 Thanks for trying it out - I'll look into this!

**Comment by diego898** [comment]
Thanks for figuring this out! By the way, do you think this will make it into the TW core? Also, should we close this issue now?

**Comment by hoelzro** [comment]
Regarding the TW core - I have a feeling it's a little too "heavy" for core, but that's ultimately up to Jeremy.

Regarding the issue, if you feel like it can be closed, we can close it!  I _think_ I'm tracking any issues reported here elsewhere, so I have no objections!

**Comment by diego898** [comment]
Ok thanks Rob!
